import type { Inspiration } from "@/types";

/**
 * The inspiration register.
 *
 * Every tile is filterable on style, season, venue type, colour and mood, so
 * the facets below are the source of truth for the gallery’s filter bar —
 * they are derived from this list rather than hard-coded beside it.
 */
export const inspiration: Inspiration[] = [
  {
    slug: "one-long-table-under-lights",
    title: "One long table, under lights",
    caption:
      "Ninety people down a single run of table. It takes a flat piece of ground and a lot of extension cable, and it is worth both.",
    imageId: "long-table",
    styleIds: ["garden", "romantic"],
    season: "summer",
    location: "Suffolk",
    venueType: "garden",
    colours: ["#7B6B4F", "#EBE3A7", "#2E2910"],
    mood: ["warm", "communal", "candlelit"],
    storySlug: "freya-and-kwame",
  },
  {
    slug: "the-hour-before",
    title: "The hour before",
    caption: "Everyone is downstairs. This is usually the only quiet part of the day.",
    imageId: "couple-quiet",
    styleIds: ["intimate", "classic"],
    season: "autumn",
    location: "Norfolk",
    venueType: "country-house",
    colours: ["#C2B3A1", "#F4F0E3", "#8A7458"],
    mood: ["quiet", "still", "morning"],
  },
  {
    slug: "flowers-from-twenty-miles",
    title: "Flowers from twenty miles",
    caption:
      "Grown, cut and arranged inside a day. Nothing flown, nothing out of season, nothing that looks like a bouquet.",
    imageId: "floral-loose",
    styleIds: ["garden", "romantic"],
    season: "spring",
    location: "Suffolk",
    venueType: "garden",
    colours: ["#B9AC9A", "#A8B273", "#E4E7CE"],
    mood: ["loose", "seasonal", "green"],
  },
  {
    slug: "shingle-and-flat-grey-sky",
    title: "Shingle and a flat grey sky",
    caption:
      "The east coast doesn’t do golden hour most of the year. Plan for the light you’ll actually get and it’s better.",
    imageId: "venue-crag-path",
    styleIds: ["coastal", "minimal"],
    season: "winter",
    location: "Aldeburgh",
    venueType: "coastal",
    colours: ["#9AA5AB", "#E7E4DA", "#3F5459"],
    mood: ["cold", "wide", "bracing"],
    storySlug: "marguerite-and-jo",
  },
  {
    slug: "letterpress-and-nothing-else",
    title: "Letterpress and nothing else",
    caption: "One weight of card, one ink, deep impression. The envelope does the rest.",
    imageId: "detail-stationery",
    styleIds: ["minimal", "classic"],
    season: "spring",
    location: "London",
    venueType: "city",
    colours: ["#CCC3B3", "#2E2910", "#FAF7EE"],
    mood: ["precise", "restrained", "tactile"],
  },
  {
    slug: "the-table-for-eight",
    title: "The table for eight",
    caption:
      "Small enough that one conversation runs the length of it. Candles lit before anyone sits down.",
    imageId: "style-intimate",
    styleIds: ["intimate", "romantic"],
    season: "autumn",
    location: "Norfolk",
    venueType: "restaurant",
    colours: ["#8A7458", "#E8DFCD", "#C7A96B"],
    mood: ["close", "warm", "low-light"],
    storySlug: "ada-and-tom",
  },
  {
    slug: "cypress-and-gravel",
    title: "Cypress and gravel",
    caption: "Southern light is flat and hard at midday. Everything moved to five o’clock.",
    imageId: "venue-la-fontaine",
    styleIds: ["destination", "classic"],
    season: "summer",
    location: "Provence",
    venueType: "chateau",
    colours: ["#93966F", "#EFE7D6", "#C9A25E"],
    mood: ["dry", "bright", "southern"],
  },
  {
    slug: "two-plain-bands",
    title: "Two plain bands",
    caption: "Both made from the same ingot by the same person, four months before.",
    imageId: "detail-rings",
    styleIds: ["minimal", "modern"],
    season: "winter",
    location: "London",
    venueType: "city",
    colours: ["#B2977A", "#F1ECE1", "#4A4322"],
    mood: ["plain", "considered", "close"],
  },
  {
    slug: "confetti-on-a-cold-morning",
    title: "Confetti on a cold morning",
    caption: "Dried petals, thrown properly. Paper is banned at most churches and rightly so.",
    imageId: "couple-confetti",
    styleIds: ["classic", "romantic"],
    season: "autumn",
    location: "Suffolk",
    venueType: "country-house",
    colours: ["#B6A288", "#EBE3A7", "#6B6340"],
    mood: ["celebratory", "traditional", "bright"],
  },
  {
    slug: "a-barn-with-the-doors-open",
    title: "A barn with the doors open",
    caption:
      "The whole point of a barn is the far end. Keep it clear, light it, and put nothing in front of it.",
    imageId: "venue-thorn-barn",
    styleIds: ["garden", "modern"],
    season: "summer",
    location: "Norfolk",
    venueType: "barn",
    colours: ["#A08A68", "#EDE7D8", "#2E2910"],
    mood: ["open", "raw", "generous"],
  },
  {
    slug: "sharing-plates-down-the-middle",
    title: "Sharing plates down the middle",
    caption:
      "Faster to serve than plated, better to eat, and it makes people talk across the table instead of along it.",
    imageId: "detail-food",
    styleIds: ["garden", "intimate"],
    season: "summer",
    location: "Suffolk",
    venueType: "garden",
    colours: ["#8D7256", "#E8DFCD", "#5C6B3C"],
    mood: ["abundant", "informal", "warm"],
  },
  {
    slug: "the-glasshouse-at-five",
    title: "The glasshouse at five",
    caption: "An hour when the glass stops being a greenhouse and starts being a room.",
    imageId: "venue-glasshouse",
    styleIds: ["garden", "romantic"],
    season: "spring",
    location: "Cambridgeshire",
    venueType: "garden",
    colours: ["#93A382", "#E4E7CE", "#3D7059"],
    mood: ["green", "filtered", "soft"],
  },
  {
    slug: "one-stem-per-setting",
    title: "One stem per setting",
    caption: "Cheaper than a centrepiece and it doesn’t block anyone’s view of anyone else.",
    imageId: "floral-single",
    styleIds: ["minimal", "modern"],
    season: "winter",
    location: "London",
    venueType: "restaurant",
    colours: ["#CEC5B6", "#FAF7EE", "#2C5745"],
    mood: ["spare", "clean", "quiet"],
  },
  {
    slug: "the-walk-back-down",
    title: "The walk back down",
    caption: "Nobody plans this bit and it’s in every set of photographs anyone keeps.",
    imageId: "couple-walk",
    styleIds: ["classic", "garden"],
    season: "summer",
    location: "Suffolk",
    venueType: "country-house",
    colours: ["#8C9578", "#EBE3A7", "#4A4322"],
    mood: ["candid", "moving", "green"],
  },
  {
    slug: "a-cake-that-tastes-of-something",
    title: "A cake that tastes of something",
    caption:
      "Undressed, cut early, served warm with the cheese. The photographs of it are worse and the cake is better.",
    imageId: "detail-cake",
    styleIds: ["minimal", "intimate"],
    season: "autumn",
    location: "Norfolk",
    venueType: "barn",
    colours: ["#D9D1C4", "#F4F0E3", "#8A7458"],
    mood: ["plain", "honest", "good"],
  },
  {
    slug: "blossom-against-plaster",
    title: "Blossom against plaster",
    caption: "Two branches in a heavy jug. It reads from the back of the room, which is the test.",
    imageId: "floral-branch",
    styleIds: ["minimal", "romantic"],
    season: "spring",
    location: "London",
    venueType: "city",
    colours: ["#CDBFB4", "#F4EDE6", "#7C5B4C"],
    mood: ["light", "sculptural", "pale"],
  },
  {
    slug: "the-hill-town-at-dusk",
    title: "The hill town at dusk",
    caption:
      "Everyone staying within four streets of each other. It turns a wedding into a weekend without anyone organising anything.",
    imageId: "style-destination",
    styleIds: ["destination", "intimate"],
    season: "summer",
    location: "Puglia",
    venueType: "chateau",
    colours: ["#7A7F79", "#C9A25E", "#EFE7D6"],
    mood: ["southern", "slow", "hosted"],
    storySlug: "sofia-and-nadine",
  },
  {
    slug: "long-dresses-short-speeches",
    title: "Long dresses, short speeches",
    caption: "Three speeches, four minutes each, before dinner. Everybody eats a hot main course.",
    imageId: "speeches",
    styleIds: ["black-tie", "classic"],
    season: "winter",
    location: "London",
    venueType: "city",
    colours: ["#6B5136", "#EBE3A7", "#1F1D1A"],
    mood: ["formal", "warm", "evening"],
  },
  {
    slug: "still-water-flat-light",
    title: "Still water, flat light",
    caption: "No sun at all and the photographs are the better for it.",
    imageId: "land-water",
    styleIds: ["coastal", "minimal"],
    season: "autumn",
    location: "Scotland",
    venueType: "coastal",
    colours: ["#9AA6A5", "#E7E4DA", "#3F5459"],
    mood: ["calm", "grey", "wide"],
  },
  {
    slug: "under-the-canopy",
    title: "Under the canopy",
    caption: "A ceremony in woodland needs a clearing and a sound system. Both are non-negotiable.",
    imageId: "venue-hollow",
    styleIds: ["garden", "intimate"],
    season: "summer",
    location: "Sussex",
    venueType: "garden",
    colours: ["#5F7050", "#A3A95C", "#EDE7D8"],
    mood: ["shaded", "green", "hushed"],
  },
  {
    slug: "the-first-dance-nobody-watched",
    title: "The first dance nobody watched",
    caption: "Started at half eleven with the floor already full. The best version of it.",
    imageId: "couple-dance",
    styleIds: ["modern", "intimate"],
    season: "summer",
    location: "Suffolk",
    venueType: "barn",
    colours: ["#3D2F22", "#EB7D00", "#EBE3A7"],
    mood: ["late", "loose", "loud"],
  },
  {
    slug: "a-room-with-nothing-in-it",
    title: "A room with nothing in it",
    caption:
      "White walls, one table, borrowed chairs. It cost less than the marquee and looked considerably better.",
    imageId: "style-minimal",
    styleIds: ["minimal", "modern"],
    season: "spring",
    location: "London",
    venueType: "city",
    colours: ["#DDD7CD", "#FAF7EE", "#2E2910"],
    mood: ["bare", "bright", "calm"],
  },
  {
    slug: "sparklers-at-eleven",
    title: "Sparklers at eleven",
    caption:
      "Buy the long ones. The short ones burn out before the last twenty people have got theirs lit.",
    imageId: "land-celebration",
    styleIds: ["romantic", "garden"],
    season: "autumn",
    location: "Norfolk",
    venueType: "barn",
    colours: ["#3A2C1F", "#EB7D00", "#EBE3A7"],
    mood: ["late", "warm", "celebratory"],
  },
  {
    slug: "the-drive-at-dusk",
    title: "The drive at dusk",
    caption: "Stone goes the right colour for about eleven minutes in September.",
    imageId: "venue-elmhurst",
    styleIds: ["classic", "black-tie"],
    season: "autumn",
    location: "Suffolk",
    venueType: "country-house",
    colours: ["#8A7161", "#EBE3A7", "#2E2910"],
    mood: ["grand", "warm", "evening"],
    storySlug: "freya-and-kwame",
  },
  {
    slug: "invitations-that-say-the-thing",
    title: "Invitations that say the thing",
    caption:
      "Date, place, time, dress, RSVP. Everything else goes on the website and stops the envelope weighing 60 grams.",
    imageId: "detail-invitations",
    styleIds: ["classic", "minimal"],
    season: "winter",
    location: "London",
    venueType: "city",
    colours: ["#C7BDA9", "#FAF7EE", "#2C5745"],
    mood: ["formal", "clear", "tactile"],
  },
  {
    slug: "an-old-car-and-a-gravel-drive",
    title: "An old car and a gravel drive",
    caption: "Book the mechanic as well as the car. Ask us why.",
    imageId: "vendor-transport",
    styleIds: ["classic", "romantic"],
    season: "summer",
    location: "Suffolk",
    venueType: "country-house",
    colours: ["#7F7A6C", "#EDE7D8", "#4A4322"],
    mood: ["traditional", "warm", "wry"],
  },
  {
    slug: "the-band-in-a-small-room",
    title: "The band in a small room",
    caption:
      "Four pieces in a room for sixty beats eight pieces in a room for two hundred, every time.",
    imageId: "vendor-music",
    styleIds: ["intimate", "modern"],
    season: "winter",
    location: "London",
    venueType: "restaurant",
    colours: ["#4A3D33", "#EB7D00", "#EBE3A7"],
    mood: ["close", "loud", "good"],
  },
  {
    slug: "morning-light-bare-floor",
    title: "Morning light, bare floor",
    caption: "The room before anything is in it. Worth seeing once, at the hour you’ll be using it.",
    imageId: "house-waking",
    styleIds: ["minimal", "classic"],
    season: "spring",
    location: "Suffolk",
    venueType: "country-house",
    colours: ["#C9BDA9", "#FAF7EE", "#8E8778"],
    mood: ["early", "still", "pale"],
  },
];

export const inspirationBySlug = Object.fromEntries(
  inspiration.map((item) => [item.slug, item]),
) as Record<string, Inspiration>;

/** Filter facets, derived from the data so they can never drift out of sync. */
export const inspirationFacets = {
  styles: [...new Set(inspiration.flatMap((i) => i.styleIds))].sort(),
  seasons: ["spring", "summer", "autumn", "winter"] as const,
  locations: [...new Set(inspiration.map((i) => i.location))].sort(),
  venueTypes: [...new Set(inspiration.map((i) => i.venueType))].sort(),
  moods: [...new Set(inspiration.flatMap((i) => i.mood))].sort(),
};
