import type { Vendor, VendorCategory } from "@/types";

export const VENDOR_CATEGORY_LABEL: Record<VendorCategory, string> = {
  photographers: "Photographers",
  videographers: "Film",
  florists: "Florists",
  caterers: "Caterers",
  "hair-makeup": "Hair & make-up",
  djs: "DJs",
  bands: "Bands",
  decor: "Decor & hire",
  stationery: "Stationery",
  cake: "Cake",
  transport: "Transport",
  dresses: "Dresses",
  suits: "Suits",
  jewellery: "Jewellery",
  planners: "Planners",
};

/**
 * Sample suppliers.
 *
 * Every one is invented, and every card and profile says so. The studio takes
 * no commission — a shortlist you can’t trust is worse than no shortlist — and
 * the copy is written the way a planner actually describes a supplier: what
 * they’re good at, and who they’re wrong for.
 */
export const vendors: Vendor[] = [
  {
    slug: "wren-and-fold",
    name: "Wren & Fold",
    category: "photographers",
    location: "Suffolk, travels",
    standfirst: "Two photographers, one of whom is always looking the other way.",
    description: [
      "Documentary, mostly on film for the day itself and digital for anything after dark. They do not pose people, which means you get twelve hours of what actually happened and about four usable frames of everyone lined up.",
      "If your mother wants formal group shots — and she will — say so early. They will do them properly and quickly, but they need to be on the running order.",
    ],
    priceBand: 3,
    priceFrom: 3400,
    travelsNationally: true,
    travelsInternationally: true,
    styleIds: ["classic", "garden", "coastal"],
    specialities: ["Documentary", "Film", "Two shooters", "Low light"],
    heroImageId: "vendor-photography",
    portfolioImageIds: ["couple-confetti", "couple-walk", "couple-quiet", "speeches", "couple-portrait", "detail-rings"],
    demo: true,
  },
  {
    slug: "iris-bell",
    name: "Iris Bell",
    category: "photographers",
    location: "Norwich",
    standfirst: "One photographer, black and white, no second shooter and no apology for it.",
    description: [
      "Works alone, shoots almost entirely in black and white, and delivers around sixty images rather than six hundred. It is a strong position and it is not for everyone.",
      "Best at small weddings where she can be genuinely invisible. At 150 guests, one person cannot be in two rooms, and she will tell you that herself.",
    ],
    priceBand: 2,
    priceFrom: 1900,
    travelsNationally: true,
    travelsInternationally: false,
    styleIds: ["intimate", "minimal", "modern"],
    specialities: ["Black and white", "Small weddings", "Reportage"],
    heroImageId: "couple-confetti",
    portfolioImageIds: ["couple-confetti", "couple-portrait", "couple-quiet", "style-intimate", "detail-rings", "couple-table"],
    demo: true,
  },
  {
    slug: "sedge-field-flowers",
    name: "Sedge Field Flowers",
    category: "florists",
    location: "near Woodbridge, Suffolk",
    standfirst: "They grow it. Cut in the morning, arranged by lunchtime, nothing flown.",
    description: [
      "A cutting garden and two polytunnels, which means the scheme is decided by what is having a good year rather than by a mood board in January.",
      "You commit to a season, not a colour. If that sounds like a compromise, it is the opposite — their September dahlias are the best thing we put on a table all year.",
    ],
    priceBand: 2,
    priceFrom: 1800,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["garden", "romantic", "classic"],
    specialities: ["Home-grown", "Seasonal only", "Loose arrangements", "Foraged foliage"],
    heroImageId: "floral-loose",
    portfolioImageIds: ["floral-loose", "floral-meadow", "floral-branch", "floral-single", "detail-table", "style-garden"],
    demo: true,
  },
  {
    slug: "saltmarsh-botanics",
    name: "Saltmarsh Botanics",
    category: "florists",
    location: "Aldeburgh",
    standfirst: "Sculptural, restrained, and built to survive coastal wind.",
    description: [
      "Architectural work — branch, grass and a single flower type rather than a mixed arrangement. It reads from the back of a room, which is the actual test.",
      "The only florist we use for anything on the shingle. Everything is engineered to stand up in weather that flattens a standard urn in ten minutes.",
    ],
    priceBand: 3,
    priceFrom: 2600,
    travelsNationally: true,
    travelsInternationally: false,
    styleIds: ["coastal", "minimal", "modern"],
    specialities: ["Sculptural", "Wind-rated", "Single-variety", "Installations"],
    heroImageId: "floral-branch",
    portfolioImageIds: ["floral-branch", "floral-single", "style-minimal", "style-coastal", "venue-crag-path", "land-water"],
    demo: true,
  },
  {
    slug: "bowline-kitchen",
    name: "Bowline Kitchen",
    category: "caterers",
    location: "Suffolk and Norfolk",
    standfirst: "Sharing plates down the middle. Faster than plated, better to eat, and people talk across the table.",
    description: [
      "Ex-restaurant kitchen doing about thirty weddings a year. Menus are short and change every six weeks, which is a good sign in a caterer and a rare one.",
      "They will not do a chicken option. If you need one, they will tell you politely to book somebody else.",
    ],
    priceBand: 3,
    priceFrom: 95,
    travelsNationally: true,
    travelsInternationally: false,
    styleIds: ["garden", "intimate", "modern"],
    specialities: ["Sharing plates", "Seasonal menus", "Wine list", "Dry-hire venues"],
    heroImageId: "detail-food",
    portfolioImageIds: ["detail-food", "detail-food-two", "long-table", "style-intimate", "detail-table", "venue-quay"],
    demo: true,
  },
  {
    slug: "ember-and-ash",
    name: "Ember & Ash",
    category: "caterers",
    location: "Norfolk, travels",
    standfirst: "Everything over fire. Twelve weddings a year, and the lamb is the reason people book them.",
    description: [
      "Whole animals, nine hours, open fire. It needs space, a fire permit and a venue that will allow it, which rules out about half the list.",
      "Worth reorganising a wedding around. We have moved a ceremony time to accommodate their cooking window and would do it again.",
    ],
    priceBand: 3,
    priceFrom: 110,
    travelsNationally: true,
    travelsInternationally: false,
    styleIds: ["garden", "intimate", "coastal"],
    specialities: ["Fire cooking", "Whole animal", "Twelve weddings a year", "Outdoor only"],
    heroImageId: "detail-food-two",
    portfolioImageIds: ["detail-food-two", "detail-food", "venue-thorn-barn", "long-table", "land-celebration", "style-garden"],
    demo: true,
  },
  {
    slug: "the-fen-six",
    name: "The Fen Six",
    category: "bands",
    location: "Cambridge",
    standfirst: "Six pieces, brass, and a set that starts at the right tempo rather than the loud one.",
    description: [
      "Soul and Motown played by people who can actually play. Two forty-five-minute sets, DJ between and after, and they will learn a first dance without charging extra for it.",
      "In a room under eighty they are too big. Ask them for the four-piece.",
    ],
    priceBand: 3,
    priceFrom: 3200,
    travelsNationally: true,
    travelsInternationally: true,
    styleIds: ["classic", "black-tie", "modern"],
    specialities: ["Six or four piece", "Brass section", "DJ included", "First dance learned"],
    heroImageId: "vendor-music",
    portfolioImageIds: ["vendor-music", "couple-dance", "land-celebration", "speeches", "style-cultural", "venue-quay"],
    demo: true,
  },
  {
    slug: "night-porter",
    name: "Night Porter",
    category: "djs",
    location: "London",
    standfirst: "A DJ who reads a room instead of a request list.",
    description: [
      "Vinyl and digital, no microphone, no announcements, no sequence of wedding standards at eleven. The floor fills and stays full, which is the entire job.",
      "Brings his own rig, which sounds better than any venue system and matters more than people expect.",
    ],
    priceBand: 2,
    priceFrom: 950,
    travelsNationally: true,
    travelsInternationally: true,
    styleIds: ["modern", "minimal", "black-tie"],
    specialities: ["Own sound system", "No mic", "Vinyl", "Late licence"],
    heroImageId: "vendor-dj",
    portfolioImageIds: ["vendor-dj", "couple-dance", "style-cultural", "land-celebration", "vendor-music", "last-dance"],
    demo: true,
  },
  {
    slug: "cold-press-studio",
    name: "Cold Press Studio",
    category: "stationery",
    location: "London",
    standfirst: "One weight of card, one ink, a deep impression. The envelope does the rest.",
    description: [
      "Letterpress on 600gsm, printed on a 1960s Heidelberg in a railway arch. Lead time is eight weeks and they will not shorten it.",
      "They will talk you out of a five-piece suite. Date, place, time, dress, RSVP — everything else goes on your wedding site and stops the envelope weighing 60 grams.",
    ],
    priceBand: 3,
    priceFrom: 1400,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["classic", "minimal", "black-tie"],
    specialities: ["Letterpress", "600gsm", "Eight-week lead", "On-the-day paper"],
    heroImageId: "detail-stationery",
    portfolioImageIds: ["detail-stationery", "detail-paper", "detail-invitations", "style-minimal", "detail-table", "detail-rings"],
    demo: true,
  },
  {
    slug: "marsh-house-bakery",
    name: "Marsh House Bakery",
    category: "cake",
    location: "Burnham Market",
    standfirst: "Cake that tastes of something. Cut early, served warm, alongside the cheese.",
    description: [
      "Undressed or barely dressed, and considerably better to eat than to photograph. That is the trade and they are upfront about it.",
      "Ask for it cut at nine and served with the cheese board rather than boxed for later. Nobody has ever regretted this.",
    ],
    priceBand: 2,
    priceFrom: 420,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["intimate", "minimal", "garden"],
    specialities: ["Undressed", "Seasonal fruit", "Cut early", "Small batch"],
    heroImageId: "detail-cake",
    portfolioImageIds: ["detail-cake", "detail-food", "style-intimate", "detail-table", "venue-thorn-barn", "detail-food-two"],
    demo: true,
  },
  {
    slug: "atelier-verge",
    name: "Atelier Verge",
    category: "dresses",
    location: "London",
    standfirst: "Made to measure in eight fittings, or altered from their rail in three.",
    description: [
      "Small atelier, four cutters, no bridal-shop theatre. They will happily make something that does not read as a wedding dress at all.",
      "Twelve months for made to measure. Under six, they will steer you to the rail, and the results are indistinguishable.",
    ],
    priceBand: 4,
    priceFrom: 3800,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["modern", "minimal", "black-tie"],
    specialities: ["Made to measure", "Eight fittings", "Non-traditional", "Alterations"],
    heroImageId: "vendor-dress",
    portfolioImageIds: ["vendor-dress", "getting-ready", "couple-portrait", "couple-quiet", "style-black-tie", "couple-street"],
    demo: true,
  },
  {
    slug: "holt-and-pike",
    name: "Holt & Pike",
    category: "suits",
    location: "London",
    standfirst: "Tailoring for people who will wear it again, which is the only sensible brief.",
    description: [
      "Half-canvas, sixteen weeks, cloth from four mills. They will not sell you a three-piece in a colour you will regret by 2029.",
      "Groomsmen at a discount if all of them come, which is the only realistic way to get five men to a fitting.",
    ],
    priceBand: 3,
    priceFrom: 1600,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["classic", "black-tie", "modern"],
    specialities: ["Half-canvas", "Sixteen weeks", "Group fittings", "British cloth"],
    heroImageId: "vendor-suit",
    portfolioImageIds: ["vendor-suit", "style-black-tie", "couple-portrait", "detail-jewellery-two", "speeches", "couple-doorway"],
    demo: true,
  },
  {
    slug: "wend-and-co",
    name: "Wend & Co",
    category: "transport",
    location: "Suffolk",
    standfirst: "Four old cars, one mechanic who travels with them. Ask us why that matters.",
    description: [
      "A 1963 estate, two saloons and a bus that seats seventeen. All of them are beautiful and all of them are sixty years old.",
      "The mechanic comes as standard. Every horror story we have about wedding transport involves a company that did not do this.",
    ],
    priceBand: 2,
    priceFrom: 600,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["classic", "romantic", "garden"],
    specialities: ["Mechanic included", "Seventeen-seat bus", "Suffolk and Norfolk", "Guest shuttles"],
    heroImageId: "vendor-transport",
    portfolioImageIds: ["vendor-transport", "couple-doorway", "venue-elmhurst", "couple-walk", "land-water", "venue-lake"],
    demo: true,
  },
  {
    slug: "june-alder",
    name: "June Alder",
    category: "hair-makeup",
    location: "Norwich, travels",
    standfirst: "Make-up that survives a coastal wind and eleven hours of being hugged.",
    description: [
      "Skin first, minimal product, and a genuine understanding of how things photograph under film versus digital.",
      "Works with a second artist for parties over six, and does the trial at your house rather than a studio so the light is honest.",
    ],
    priceBand: 2,
    priceFrom: 480,
    travelsNationally: true,
    travelsInternationally: true,
    styleIds: ["coastal", "minimal", "romantic"],
    specialities: ["Skin-first", "Weather-proof", "Home trials", "Second artist available"],
    heroImageId: "vendor-beauty",
    portfolioImageIds: ["vendor-beauty", "couple-quiet", "getting-ready", "couple-portrait", "detail-jewellery", "couple-window"],
    demo: true,
  },
  {
    slug: "hallmark-jewellers",
    name: "Fen & Hallmark",
    category: "jewellery",
    location: "Cambridge",
    standfirst: "Two bands from the same ingot, made by the person who hands them to you.",
    description: [
      "A workshop rather than a shop. Four months, one fitting, and you can watch the pour if you want to.",
      "Recycled gold as standard, and they will remake a family ring into something wearable rather than selling you new metal.",
    ],
    priceBand: 3,
    priceFrom: 1450,
    travelsNationally: false,
    travelsInternationally: false,
    styleIds: ["minimal", "classic", "modern"],
    specialities: ["Same-ingot pairs", "Recycled gold", "Remodelling", "Four-month lead"],
    heroImageId: "detail-jewellery",
    portfolioImageIds: ["detail-jewellery", "detail-jewellery-two", "detail-rings", "style-minimal", "couple-portrait", "floral-single"],
    demo: true,
  },
  {
    slug: "pale-light-films",
    name: "Pale Light Films",
    category: "videographers",
    location: "London, travels",
    standfirst: "Eight minutes, no drone, no slow-motion walking, no licensed pop song.",
    description: [
      "Sound-led — they mic the ceremony and the speeches properly, and the film is built around what people said rather than what the light did.",
      "One film, eight minutes, delivered in six weeks. No four-hour documentary edit that nobody watches twice.",
    ],
    priceBand: 3,
    priceFrom: 2400,
    travelsNationally: true,
    travelsInternationally: true,
    styleIds: ["modern", "intimate", "destination"],
    specialities: ["Sound-led", "Eight-minute film", "Six-week delivery", "No drone"],
    heroImageId: "vendor-photography",
    portfolioImageIds: ["speeches", "couple-walk", "couple-dance", "couple-confetti", "style-destination", "land-celebration"],
    demo: true,
  },
];

export const vendorBySlug = Object.fromEntries(
  vendors.map((vendor) => [vendor.slug, vendor]),
) as Record<string, Vendor>;

export const vendorFacets = {
  categories: [...new Set(vendors.map((vendor) => vendor.category))],
  locations: [...new Set(vendors.map((vendor) => vendor.location))].sort(),
  styles: [...new Set(vendors.flatMap((vendor) => vendor.styleIds))].sort(),
};
