import type { Venue, VenueType } from "@/types";

/**
 * Sample venues.
 *
 * Invented, and the UI says so wherever they appear. Prices are indicative
 * bands rather than quotes — no real venue’s pricing is reproduced here.
 */
export const venues: Venue[] = [
  {
    slug: "elmhurst-house",
    name: "Elmhurst House",
    location: "near Framlingham",
    region: "Suffolk",
    country: "GB",
    type: "country-house",
    standfirst:
      "Early Georgian, ninety seconds from ceremony lawn to dining room, and the stone goes an impossible colour in September.",
    description: [
      "The reason we keep coming back is the walk. Ceremony on the south lawn, drinks on the terrace, dinner in the orangery — the whole thing under two minutes, with no corridor for a hundred and forty people to bottleneck in.",
      "The orangery seats a hundred and forty-four on three long runs, which is unusual; most rooms this size force you into rounds. Overhead light is poor, so plan on candles from seven.",
      "Exclusive use is Friday afternoon to Sunday morning. Fourteen bedrooms in the house, more in the coach house.",
    ],
    capacitySeated: 144,
    capacityStanding: 200,
    priceBand: 3,
    priceFrom: 9500,
    priceTo: 16000,
    indoor: true,
    outdoor: true,
    accommodation: 22,
    exclusiveUse: true,
    styleIds: ["classic", "garden"],
    features: [
      "Three long runs of table, no rounds required",
      "Ceremony licence, south lawn and library",
      "Ninety seconds ceremony to dinner",
      "Kitchen for outside caterers",
      "Twenty-two beds on site",
      "Fireworks permitted until 11pm",
    ],
    heroImageId: "venue-elmhurst",
    galleryImageIds: ["venue-elmhurst", "first-light", "long-table", "couple-garden", "floral-loose", "detail-table"],
    coordinates: { lat: 52.2213, lng: 1.3436 },
    availability: ["spring", "autumn", "winter"],
    faqs: [
      {
        question: "Can we bring our own caterer?",
        answer: "Yes, from an approved list of six. The kitchen is fully equipped and there is no corkage on wine you supply.",
      },
      {
        question: "What happens if it rains on the ceremony?",
        answer: "The library is licensed and seats a hundred and twenty. It is a genuinely good room, not a fallback.",
      },
    ],
  },
  {
    slug: "the-thorn-barn",
    name: "The Thorn Barn",
    location: "near Burnham Market",
    region: "Norfolk",
    country: "GB",
    type: "barn",
    standfirst:
      "A working barn with the far doors opening onto twelve acres. Cold in February, which is why it costs a third of what it does in July.",
    description: [
      "The point of this room is the far end: forty feet of open doorway with nothing but field behind it. Keep it clear, light it, and put nothing in front of it.",
      "Bare brick and oak, no fixed lighting, no fixed anything. Everything comes in, which is more work and considerably more freedom.",
      "In winter you will need six indirect heaters running from seven in the morning. Budget for it properly — it is the single thing guests notice within a minute of arriving.",
    ],
    capacitySeated: 110,
    capacityStanding: 160,
    priceBand: 2,
    priceFrom: 3200,
    priceTo: 9000,
    indoor: true,
    outdoor: true,
    accommodation: 8,
    exclusiveUse: true,
    styleIds: ["garden", "intimate", "minimal"],
    features: [
      "Forty-foot open doorway to the field",
      "Dry hire, three-day access",
      "No fixed lighting — bring your own scheme",
      "Fire pit and outdoor cooking permitted",
      "Eight beds in the granary",
      "Music until midnight",
    ],
    heroImageId: "venue-quay",
    galleryImageIds: ["venue-quay", "style-intimate", "detail-food", "couple-table", "land-light", "detail-cake"],
    coordinates: { lat: 52.9469, lng: 0.7305 },
    availability: ["winter", "spring", "summer", "autumn"],
    faqs: [
      {
        question: "Is it heated?",
        answer: "Not built in. We hire six indirect diesel heaters for winter weddings — about £900 for the weekend and worth every penny.",
      },
      {
        question: "How late can music run?",
        answer: "Midnight inside with the doors shut, 10pm outside. The nearest house is 400 metres away and they are reasonable about it.",
      },
    ],
  },
  {
    slug: "the-net-shed",
    name: "The Net Shed",
    location: "Aldeburgh",
    region: "Suffolk",
    country: "GB",
    type: "coastal",
    standfirst:
      "Black timber on the shingle, doors that open straight onto the North Sea, and weather that is part of the design rather than a risk to it.",
    description: [
      "A working fisherman’s shed until 1994, now a single long room with doors at both ends and a floor that has seen worse than a dance.",
      "You cannot fight the weather here, so we stop trying. The room is designed to be used with the doors open in any conditions — a ceremony with rain going past horizontally four feet away is the best one we have ever run.",
      "Ninety seated, and that is a hard number. The building will not take more.",
    ],
    capacitySeated: 90,
    capacityStanding: 130,
    priceBand: 2,
    priceFrom: 4200,
    priceTo: 7500,
    indoor: true,
    outdoor: true,
    accommodation: 0,
    exclusiveUse: true,
    styleIds: ["coastal", "modern", "intimate"],
    features: [
      "Doors at both ends, open in any weather",
      "Directly on the shingle",
      "Beach ceremony permitted with council notice",
      "Dry hire, own caterer",
      "Hard ninety-seat limit",
      "Aldeburgh town four minutes on foot",
    ],
    heroImageId: "golden-hour",
    galleryImageIds: ["golden-hour", "couple-confetti", "land-water", "couple-coast", "style-coastal", "detail-toast"],
    coordinates: { lat: 52.1533, lng: 1.6047 },
    availability: ["spring", "autumn", "winter"],
    faqs: [
      {
        question: "What if the weather is genuinely bad?",
        answer: "The ceremony moves inside with the doors still open. We design the indoor version first and treat the beach as the upgrade — it inverts the whole problem.",
      },
      {
        question: "Is there parking?",
        answer: "Six spaces. Everyone else uses the town car park, four minutes away, or the minibus loop we run for most weddings here.",
      },
    ],
  },
  {
    slug: "masseria-torreluna",
    name: "Masseria Torreluna",
    location: "near Ostuni",
    region: "Puglia",
    country: "IT",
    type: "chateau",
    standfirst:
      "A fortified farmhouse with eleven rooms, four hectares of olives and a stone terrace that faces west. Take it for five nights, not one.",
    description: [
      "The terrace is the whole argument: forty metres of it, facing directly into the sunset, with a wall low enough to sit on and high enough to stop the wind.",
      "Eleven bedrooms means immediate family on site and everyone else in Ostuni, eight minutes away. We run two minibuses on a loop from six until two, and it works better than hire cars ever do.",
      "Book the whole week either side of the wedding if you can. The Friday dinner under the olives changes the sound of the room on Saturday.",
    ],
    capacitySeated: 120,
    capacityStanding: 180,
    priceBand: 3,
    priceFrom: 11000,
    priceTo: 22000,
    indoor: true,
    outdoor: true,
    accommodation: 24,
    exclusiveUse: true,
    styleIds: ["destination", "intimate", "romantic"],
    features: [
      "Forty-metre west-facing terrace",
      "Five-night exclusive use",
      "In-house kitchen, or bring your own",
      "Eleven rooms sleeping twenty-four",
      "Single-track access — minibuses essential",
      "Civil ceremony in Ostuni, eight minutes away",
    ],
    heroImageId: "style-destination",
    galleryImageIds: ["style-destination", "venue-la-fontaine", "long-table", "couple-dusk", "detail-food", "couple-street"],
    coordinates: { lat: 40.7297, lng: 17.5773 },
    availability: ["spring", "summer", "autumn"],
    faqs: [
      {
        question: "Can we get legally married there?",
        answer: "Not at the masseria. The civil ceremony happens at the Ostuni town hall — twenty minutes, eleven people — and the ceremony that matters happens on the terrace at eight.",
      },
      {
        question: "How do guests get around?",
        answer: "Two minibuses on a fixed loop from Ostuni, six until two. Ask people not to hire cars: the lane has one passing place.",
      },
    ],
  },
  {
    slug: "the-glasshouse",
    name: "The Glasshouse",
    location: "near Cambridge",
    region: "Cambridgeshire",
    country: "GB",
    type: "garden",
    standfirst:
      "Victorian iron and glass in a walled garden. Unusable at midday in July, and perfect at five o’clock in May.",
    description: [
      "A restored palm house, eighty feet long, still full of plants. The light through the glass at the end of the day is the reason to book it and the reason to keep the ceremony late.",
      "It is a greenhouse, which means it behaves like one. High summer at noon is genuinely too hot; spring and autumn are ideal, and a winter wedding here with the heaters on is quietly spectacular.",
      "The walled garden takes a marquee if you need more room, though we would argue for keeping it small.",
    ],
    capacitySeated: 96,
    capacityStanding: 140,
    priceBand: 3,
    priceFrom: 6800,
    priceTo: 11500,
    indoor: true,
    outdoor: true,
    accommodation: 0,
    exclusiveUse: true,
    styleIds: ["garden", "romantic", "modern"],
    features: [
      "Eighty-foot Victorian palm house",
      "Walled garden for drinks or marquee",
      "Ceremony licence inside and out",
      "Planting maintained year round",
      "Approved caterer list of four",
      "Music until 11.30pm",
    ],
    heroImageId: "land-light",
    galleryImageIds: ["land-light", "floral-branch", "style-garden", "couple-walk", "land-light", "floral-single"],
    coordinates: { lat: 52.1936, lng: 0.1247 },
    availability: ["spring", "autumn", "winter"],
    faqs: [
      {
        question: "Is it too hot in summer?",
        answer: "At midday in July, yes. We push ceremonies here to five o’clock from June to August, which is a better hour anyway.",
      },
      {
        question: "Can we have the ceremony outside?",
        answer: "Yes — the walled garden is licensed, with the glasshouse as the wet-weather plan. Same flowers, same room, ninety different minutes.",
      },
    ],
  },
  {
    slug: "quay-street",
    name: "Quay Street",
    location: "Shoreditch, London",
    region: "London",
    country: "GB",
    type: "restaurant",
    standfirst:
      "A restaurant that closes for you. Sixty people, one room, and food that is the actual reason you booked it.",
    description: [
      "Not a wedding venue, which is the point. It is a restaurant with a kitchen that does this every night, and on a Sunday they will close and cook for you.",
      "Sixty seated across four tables or one long run of fifty-six if you are willing to lose a few. Exposed brick, filament light, no styling required and honestly none wanted.",
      "There is no ceremony licence. Most couples do the registry office at Hackney in the morning and walk here.",
    ],
    capacitySeated: 60,
    capacityStanding: 90,
    priceBand: 3,
    priceFrom: 5500,
    priceTo: 12000,
    indoor: true,
    outdoor: false,
    accommodation: 0,
    exclusiveUse: true,
    styleIds: ["intimate", "modern", "minimal"],
    features: [
      "Full restaurant closure, Sundays",
      "In-house kitchen, no outside catering",
      "One long table of fifty-six possible",
      "Wine list rather than a package",
      "No styling needed",
      "Hackney registry office eleven minutes away",
    ],
    heroImageId: "long-table",
    galleryImageIds: ["long-table", "long-table", "detail-food", "style-intimate", "couple-table", "detail-food-two"],
    coordinates: { lat: 51.5265, lng: -0.0785 },
    availability: ["winter", "spring", "summer", "autumn"],
    faqs: [
      {
        question: "Can we get married there?",
        answer: "No licence. Hackney registry office is eleven minutes' walk and most couples do the legal bit at eleven and arrive here at one.",
      },
      {
        question: "Can we bring our own wine?",
        answer: "Corkage is £25 a bottle, which is steep until you see the list. Most people give in and use theirs.",
      },
    ],
  },
  {
    slug: "hollow-lane",
    name: "Hollow Lane",
    location: "near Petworth",
    region: "West Sussex",
    country: "GB",
    type: "garden",
    standfirst:
      "A clearing in forty acres of beech, at the end of a sunken lane. You will need a generator, a sound system and good shoes.",
    description: [
      "The clearing is about thirty metres across with beech on every side and a canopy that holds the light in a way no marquee ever manages.",
      "Nothing is here. No power, no water, no cover. Everything comes in down a track that a lorry can just about manage in dry weather, which is a real constraint on the design and worth taking seriously.",
      "In return you get a ceremony space that nobody has seen before, forty minutes from London.",
    ],
    capacitySeated: 80,
    capacityStanding: 120,
    priceBand: 1,
    priceFrom: 1800,
    priceTo: 4500,
    indoor: false,
    outdoor: true,
    accommodation: 0,
    exclusiveUse: true,
    styleIds: ["garden", "intimate", "minimal"],
    features: [
      "Thirty-metre clearing in mature beech",
      "Completely blank — everything comes in",
      "Generator and sound system essential",
      "Track access, dry weather only for lorries",
      "Camping permitted for forty",
      "No licence — ceremony is symbolic",
    ],
    heroImageId: "venue-hollow",
    galleryImageIds: ["venue-hollow", "land-forest", "couple-walk", "floral-meadow", "land-light", "land-tree"],
    coordinates: { lat: 50.9861, lng: -0.6103 },
    availability: ["spring", "summer"],
    faqs: [
      {
        question: "What about the loos?",
        answer: "Hired, and worth spending on. The difference between adequate and good here is about £600 and it is the most commented-on line in the budget.",
      },
      {
        question: "Is there a wet-weather plan?",
        answer: "A marquee, booked provisionally from month two. In woodland it is not optional — the ground goes in an hour.",
      },
    ],
  },
  {
    slug: "castello-di-mirandola",
    name: "Castello di Mirandola",
    location: "Val d’Orcia",
    region: "Tuscany",
    country: "IT",
    type: "castle",
    standfirst:
      "Eleventh-century stone on a ridge with the whole valley below it. Formal, enormous, and not remotely subtle.",
    description: [
      "There is no understating this building. It sits alone on a ridge and everything for twenty miles looks up at it, which suits some weddings and overwhelms others.",
      "The great hall seats two hundred and twenty under a barrel vault. Acoustically it is a challenge; anything amplified needs a proper engineer rather than a band with a PA.",
      "Black tie belongs here. Anything more relaxed tends to lose an argument with the architecture.",
    ],
    capacitySeated: 220,
    capacityStanding: 320,
    priceBand: 4,
    priceFrom: 24000,
    priceTo: 48000,
    indoor: true,
    outdoor: true,
    accommodation: 34,
    exclusiveUse: true,
    styleIds: ["black-tie", "destination", "classic"],
    features: [
      "Great hall seating 220 under a barrel vault",
      "Ridge-top terrace for ceremonies",
      "Thirty-four rooms in the castle and borgo",
      "In-house production and lighting team",
      "Sound engineer required for live music",
      "Helicopter landing permitted",
    ],
    heroImageId: "venue-castello",
    galleryImageIds: ["venue-castello", "style-black-tie", "style-classic", "couple-portrait", "detail-jewellery", "speeches"],
    coordinates: { lat: 43.0464, lng: 11.6136 },
    availability: ["spring", "summer", "autumn"],
    faqs: [
      {
        question: "Is it as expensive as it looks?",
        answer: "Yes. Hire is the smaller half of it — production, lighting and staffing a building this size is where the money goes.",
      },
      {
        question: "Can we have live music in the hall?",
        answer: "With a sound engineer, yes, and it is extraordinary. Without one it is a barrel vault full of mud.",
      },
    ],
  },
];

export const venueBySlug = Object.fromEntries(
  venues.map((venue) => [venue.slug, venue]),
) as Record<string, Venue>;

export const VENUE_TYPE_LABEL: Record<VenueType, string> = {
  "country-house": "Country house",
  barn: "Barn",
  coastal: "Coastal",
  garden: "Garden",
  city: "City",
  chateau: "Château & masseria",
  vineyard: "Vineyard",
  castle: "Castle",
  restaurant: "Restaurant",
  marquee: "Marquee",
};

export const venueFacets = {
  types: [...new Set(venues.map((venue) => venue.type))],
  regions: [...new Set(venues.map((venue) => venue.region))].sort(),
  styles: [...new Set(venues.flatMap((venue) => venue.styleIds))].sort(),
};
